server:
  port: 8080
spring:
  profiles:
    active: test

---

person:
  lastName: 张三
  age: 18
  boss: false
  map: {k1: v1,k2: 12}
  dog:
    name: wangwang
    age: 2
spring:
  profiles: dev

---

person:
  lastName: 李四
  age: 18
  boss: false
  map: {k1: v1,k2: 12}
  dog:
    name: wangwang
    age: 2

server:
  servlet:
    context-path: /boot
logging:
  level:
    com.hjc: warn
  file: spring.log

spring:
  profiles: test



